import type { PaletteKey } from '../types';

interface PaletteColors {
  primary: string;
  primaryLight: string;
  primaryDark: string;
  secondary: string;
  accent: string;
  bg: string;
  surface: string;
  text: string;
  textMuted: string;
  border: string;
}

export const palettes: Record<Exclude<PaletteKey, 'custom'>, PaletteColors> = {
  'nature': {
    primary: '#3E7B57',
    primaryLight: '#5A9E74',
    primaryDark: '#2B5840',
    secondary: '#EFF7EC',
    accent: '#C9A93C',
    bg: '#F8FCF6',
    surface: '#FFFFFF',
    text: '#1C2D22',
    textMuted: '#5D7A67',
    border: '#C4D9CA',
  },
  'rose-gold': {
    primary: '#B76E79',
    primaryLight: '#D4939D',
    primaryDark: '#8F4652',
    secondary: '#F5F0EB',
    accent: '#C9A84C',
    bg: '#FAF7F2',
    surface: '#FFFFFF',
    text: '#2A1F1A',
    textMuted: '#8B7355',
    border: '#E8DDD4',
  },
  'garden': {
    primary: '#5E7D5B',
    primaryLight: '#80A07D',
    primaryDark: '#3C5A39',
    secondary: '#F2F5EE',
    accent: '#C4A45A',
    bg: '#F8F9F5',
    surface: '#FFFFFF',
    text: '#1E2D1B',
    textMuted: '#6B7B5A',
    border: '#D8E4D0',
  },
  'navy-gold': {
    primary: '#1C2D5A',
    primaryLight: '#2D4480',
    primaryDark: '#0F1A38',
    secondary: '#F8F5EE',
    accent: '#C9A84C',
    bg: '#F8F5EE',
    surface: '#FFFFFF',
    text: '#0F1835',
    textMuted: '#5A6070',
    border: '#D5C9A8',
  },
  'sage': {
    primary: '#8FA68A',
    primaryLight: '#A8C0A3',
    primaryDark: '#6B8066',
    secondary: '#F5F3EF',
    accent: '#C4B5A5',
    bg: '#FAFAF7',
    surface: '#FFFFFF',
    text: '#2D2D2D',
    textMuted: '#7A7A7A',
    border: '#E0DBD3',
  },
  'midnight': {
    primary: '#9B5A6A',
    primaryLight: '#BB7A8A',
    primaryDark: '#73384A',
    secondary: '#23213A',
    accent: '#E8C977',
    bg: '#13111E',
    surface: '#1E1C2E',
    text: '#F0E6DC',
    textMuted: '#A09080',
    border: '#30283C',
  },
  'platinum': {
    primary: '#2C3E50',
    primaryLight: '#34495E',
    primaryDark: '#1A252F',
    secondary: '#ECF0F1',
    accent: '#E74C3C',
    bg: '#F8F9FA',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textMuted: '#7F8C8D',
    border: '#BDC3C7',
  },
  'sapphire': {
    primary: '#003A70',
    primaryLight: '#0D5AAE',
    primaryDark: '#001F3F',
    secondary: '#F0F4F8',
    accent: '#FFB81C',
    bg: '#FAFBFC',
    surface: '#FFFFFF',
    text: '#001F3F',
    textMuted: '#5A6C7D',
    border: '#D0D8E0',
  },
  'emerald': {
    primary: '#027A48',
    primaryLight: '#0FA968',
    primaryDark: '#084B2E',
    secondary: '#E7F5F0',
    accent: '#F59E0B',
    bg: '#F6FFFE',
    surface: '#FFFFFF',
    text: '#082C2C',
    textMuted: '#5B6E6B',
    border: '#C8D7D5',
  },
  'coral': {
    primary: '#FF6B6B',
    primaryLight: '#FF8787',
    primaryDark: '#FF4757',
    secondary: '#FEF5F5',
    accent: '#00B4DB',
    bg: '#FFFAFA',
    surface: '#FFFFFF',
    text: '#2A2A2A',
    textMuted: '#7A7A7A',
    border: '#E8C1C1',
  },
  'lavender': {
    primary: '#7C3AED',
    primaryLight: '#A78BFA',
    primaryDark: '#5B21B6',
    secondary: '#F3F0FF',
    accent: '#FCD34D',
    bg: '#FAFBFF',
    surface: '#FFFFFF',
    text: '#2D1B4E',
    textMuted: '#8B7BA8',
    border: '#E9D5FF',
  },
  'teal': {
    primary: '#0D9488',
    primaryLight: '#14B8A6',
    primaryDark: '#0F766E',
    secondary: '#F0FDFA',
    accent: '#EA580C',
    bg: '#F8FFFE',
    surface: '#FFFFFF',
    text: '#134E4A',
    textMuted: '#5A7A78',
    border: '#C4E8E4',
  },
  'burgundy': {
    primary: '#6B2542',
    primaryLight: '#8B3A62',
    primaryDark: '#4A1533',
    secondary: '#FAF3F7',
    accent: '#D4AF37',
    bg: '#FFFBFD',
    surface: '#FFFFFF',
    text: '#3D1F2A',
    textMuted: '#7B5A6F',
    border: '#E8D5E0',
  },
  'gold-premium': {
    primary: '#B8860B',
    primaryLight: '#DAA520',
    primaryDark: '#8B6908',
    secondary: '#FEF9E7',
    accent: '#2C3E50',
    bg: '#FFFEF8',
    surface: '#FFFFFF',
    text: '#3D2817',
    textMuted: '#8B7355',
    border: '#E8DCC4',
  },
  'ocean': {
    primary: '#0369A1',
    primaryLight: '#0284C7',
    primaryDark: '#075985',
    secondary: '#F0F9FF',
    accent: '#EF4444',
    bg: '#F8FCFE',
    surface: '#FFFFFF',
    text: '#082F49',
    textMuted: '#475569',
    border: '#BAE6FD',
  },
  'mint': {
    primary: '#0D9488',
    primaryLight: '#2DD4BF',
    primaryDark: '#0F766E',
    secondary: '#F0FDFA',
    accent: '#FB923C',
    bg: '#F6FFFE',
    surface: '#FFFFFF',
    text: '#134E4A',
    textMuted: '#4D8077',
    border: '#99F6E4',
  },
  'peach': {
    primary: '#F97316',
    primaryLight: '#FB923C',
    primaryDark: '#EA580C',
    secondary: '#FFF7ED',
    accent: '#8B5CF6',
    bg: '#FFFAF7',
    surface: '#FFFFFF',
    text: '#431407',
    textMuted: '#9A4A26',
    border: '#FED7AA',
  },
  'denim': {
    primary: '#1D4ED8',
    primaryLight: '#3B82F6',
    primaryDark: '#1E3A8A',
    secondary: '#EFF6FF',
    accent: '#F59E0B',
    bg: '#F8FAFF',
    surface: '#FFFFFF',
    text: '#1E3A5F',
    textMuted: '#4A6080',
    border: '#BFDBFE',
  },
  'mustard': {
    primary: '#D97706',
    primaryLight: '#F59E0B',
    primaryDark: '#B45309',
    secondary: '#FFFBEB',
    accent: '#7C3AED',
    bg: '#FFFDF0',
    surface: '#FFFFFF',
    text: '#2D1A00',
    textMuted: '#7A6520',
    border: '#FDE68A',
  },
  'cream': {
    primary: '#92400E',
    primaryLight: '#B45309',
    primaryDark: '#78350F',
    secondary: '#FDF8F0',
    accent: '#065F46',
    bg: '#FFFDF5',
    surface: '#FFFFFF',
    text: '#1C0A00',
    textMuted: '#78584A',
    border: '#E7D5C0',
  },
  'olive': {
    primary: '#4F6835',
    primaryLight: '#6E8F4A',
    primaryDark: '#354825',
    secondary: '#F5EFE0',
    accent: '#C9A84C',
    bg: '#F8F3E8',
    surface: '#FFFFFF',
    text: '#2A2217',
    textMuted: '#6E6050',
    border: '#D6C9A5',
  },
};

const cssVarMap: Record<keyof PaletteColors, string> = {
  primary: '--color-primary',
  primaryLight: '--color-primary-light',
  primaryDark: '--color-primary-dark',
  secondary: '--color-secondary',
  accent: '--color-accent',
  bg: '--color-bg',
  surface: '--color-surface',
  text: '--color-text',
  textMuted: '--color-text-muted',
  border: '--color-border',
};

export function applyTheme(palette: PaletteKey, customColors?: Partial<PaletteColors>): void {
  const base = palette !== 'custom' ? palettes[palette] : palettes['rose-gold'];
  const colors: PaletteColors = { ...base, ...customColors };
  const root = document.documentElement;

  (Object.keys(cssVarMap) as Array<keyof PaletteColors>).forEach((key) => {
    root.style.setProperty(cssVarMap[key], colors[key]);
  });
}

export function applyFonts(heading: string, subheading: string, body: string): void {
  const root = document.documentElement;
  root.style.setProperty('--font-heading', `'${heading}', Georgia, serif`);
  root.style.setProperty('--font-subheading', `'${subheading}', Georgia, serif`);
  root.style.setProperty('--font-body', `'${body}', system-ui, sans-serif`);
}
